INSERT INTO classroom(name,capacity) VALUES ('Pr1',25);
INSERT INTO classroom(name,capacity) VALUES ('Pr2',25);
INSERT INTO classroom(name,capacity) VALUES ('Pr3',25);
INSERT INTO classroom(name,capacity) VALUES ('Pr4',10);
INSERT INTO classroom(name,capacity) VALUES ('Pr5',10);
INSERT INTO classroom(name,capacity) VALUES ('001',50);
INSERT INTO classroom(name,capacity) VALUES ('002',30);
INSERT INTO classroom(name,capacity) VALUES ('003',200);
INSERT INTO classroom(name,capacity) VALUES ('004',50);
INSERT INTO classroom(name,capacity) VALUES ('005',50);
INSERT INTO classroom(name,capacity) VALUES ('006',50);
INSERT INTO classroom(name,capacity) VALUES ('101',50);
INSERT INTO classroom(name,capacity) VALUES ('103',25);
INSERT INTO classroom(name,capacity) VALUES ('104',25);
INSERT INTO classroom(name,capacity) VALUES ('105',25);
INSERT INTO classroom(name,capacity) VALUES ('106',25);
INSERT INTO classroom(name,capacity) VALUES ('107',25);
INSERT INTO classroom(name,capacity) VALUES ('108',25);
INSERT INTO classroom(name,capacity) VALUES ('109',50);
INSERT INTO classroom(name,capacity) VALUES ('A001',50);
INSERT INTO classroom(name,capacity) VALUES ('A002',50);
INSERT INTO classroom(name,capacity) VALUES ('A101',50);
INSERT INTO classroom(name,capacity) VALUES ('A102',200);
INSERT INTO classroom(name,capacity) VALUES ('Martinovka',200);
INSERT INTO classroom(name,capacity) VALUES ('Odsjek Fizika',100);
INSERT INTO classroom(name,capacity) VALUES ('Odsjek Kemija',100);
