INSERT INTO course(id,name) VALUES (1,'Matematička analiza 1 (p)');
INSERT INTO course(id,name) VALUES (2,'Matematička analiza 1 (v)');
INSERT INTO course(id,name) VALUES (3,'Linearna algebra 1 (p)');
INSERT INTO course(id,name) VALUES (4,'Linearna algebra 1  (v)');
INSERT INTO course(id,name) VALUES (5,'Elementarna matematika 1 (p)');
INSERT INTO course(id,name) VALUES (6,'Elementarna matematika 1  (v)');
INSERT INTO course(id,name) VALUES (7,'Programiranje 1 (p)');
INSERT INTO course(id,name) VALUES (8,'Programiranje 1  (v)');
INSERT INTO course(id,name) VALUES (9,'Tjelesna i zdravstvena kultura 1 (v)');
INSERT INTO course(id,name) VALUES (10,'Matematička analiza 2 (p)');
INSERT INTO course(id,name) VALUES (11,'Matematička analiza 2  (v)');
INSERT INTO course(id,name) VALUES (12,'Linearna algebra 2 (p)');
INSERT INTO course(id,name) VALUES (13,'Linearna algebra 2  (v)');
INSERT INTO course(id,name) VALUES (14,'Elementarna matematika 2 (p)');
INSERT INTO course(id,name) VALUES (15,'Elementarna matematika 2  (v)');
INSERT INTO course(id,name) VALUES (16,'Programiranje 2 (p)');
INSERT INTO course(id,name) VALUES (17,'Programiranje 2 (v)');
INSERT INTO course(id,name) VALUES (18,'Tjelesna i zdravstvena kultura 2 (v)');
INSERT INTO course(id,name) VALUES (19,'Diferencijalni račun funkcija više varijabli (p)');
INSERT INTO course(id,name) VALUES (20,'Diferencijalni račun funkcija više varijabli (v)');
INSERT INTO course(id,name) VALUES (21,'Diskretna matematika (p)');
INSERT INTO course(id,name) VALUES (22,'Diskretna matematika (v)');
INSERT INTO course(id,name) VALUES (23,'Vjerorajtnost (p)');
INSERT INTO course(id,name) VALUES (24,'Vjerorajtnost (v)');
INSERT INTO course(id,name) VALUES (25,'Strukture podataka i algoritmi  (p)');
INSERT INTO course(id,name) VALUES (26,'Strukture podataka i algoritmi  (v)');
INSERT INTO course(id,name) VALUES (27,'Engleski jezik struke 1 (p)');
INSERT INTO course(id,name) VALUES (28,'Engleski jezik struke 1 (v)');
INSERT INTO course(id,name) VALUES (29,'Fizika 1 (p)');
INSERT INTO course(id,name) VALUES (30,'Fizika 1 (v)');
INSERT INTO course(id,name) VALUES (31,'Matematičko modeliranje u biologiji (p)');
INSERT INTO course(id,name) VALUES (32,'Matematičko modeliranje u biologiji (v)');
INSERT INTO course(id,name) VALUES (33,'Matematičke metode u kristalografiji i općoj kemiji (p)');
INSERT INTO course(id,name) VALUES (34,'Matematičke metode u kristalografiji i općoj kemiji (v)');
INSERT INTO course(id,name) VALUES (35,'Građa računala (p)');
INSERT INTO course(id,name) VALUES (36,'Građa računala (v)');
INSERT INTO course(id,name) VALUES (37,'Algebarske strukture (p)');
INSERT INTO course(id,name) VALUES (38,'Algebarske strukture (v)');
INSERT INTO course(id,name) VALUES (39,'Obične diferencijalne jednadžbe (p)');
INSERT INTO course(id,name) VALUES (40,'Obične diferencijalne jednadžbe (v)');
INSERT INTO course(id,name) VALUES (41,'Vektorski prostori (p)');
INSERT INTO course(id,name) VALUES (42,'Vektorski prostori (v)');
INSERT INTO course(id,name) VALUES (43,'Teorija skupova (p)');
INSERT INTO course(id,name) VALUES (44,'Teorija skupova (v)');
INSERT INTO course(id,name) VALUES (45,'Matematička logika (p)');
INSERT INTO course(id,name) VALUES (46,'Matematička logika (v)');
INSERT INTO course(id,name) VALUES (47,'Iterativne metode (p)');
INSERT INTO course(id,name) VALUES (48,'Iterativne metode (v)');
INSERT INTO course(id,name) VALUES (49,'Markovljevi lanci (p)');
INSERT INTO course(id,name) VALUES (50,'Markovljevi lanci (v)');
INSERT INTO course(id,name) VALUES (51,'Euklidski prostori (p)');
INSERT INTO course(id,name) VALUES (52,'Euklidski prostori (v)');
INSERT INTO course(id,name) VALUES (53,'Mreže računala (p)');
INSERT INTO course(id,name) VALUES (54,'Mreže računala (v)');
