INSERT INTO "group"(id,name,members,parent_id) VALUES (1,'PDM 1. godina [A-LJ]',100,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (2,'PDM 1. godina [A-H]',50,1);
INSERT INTO "group"(id,name,members,parent_id) VALUES (3,'PDM 1. godina [I-LJ]',50,1);
INSERT INTO "group"(id,name,members,parent_id) VALUES (4,'PDM 1. godina [M-Ž]',100,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (5,'PDM 1. godina [M-P]',50,4);
INSERT INTO "group"(id,name,members,parent_id) VALUES (6,'PDM 1. godina [R-Ž]',50,4);
INSERT INTO "group"(id,name,members,parent_id) VALUES (7,'PDM 2. godina [A-LJ]',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (8,'PDM 2. godina [A-J]',40,7);
INSERT INTO "group"(id,name,members,parent_id) VALUES (9,'PDM 2. godina [K-LJ]',40,7);
INSERT INTO "group"(id,name,members,parent_id) VALUES (10,'PDM 2. godina [M-Ž]',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (11,'PDM 2. godina [M-P]',40,10);
INSERT INTO "group"(id,name,members,parent_id) VALUES (12,'PDM 2. godina [R-Ž]',40,10);
INSERT INTO "group"(id,name,members,parent_id) VALUES (13,'PDM 3. godina [A-LJ]',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (14,'PDM 3. godina [A-H]',40,13);
INSERT INTO "group"(id,name,members,parent_id) VALUES (15,'PDM 3. godina [I-LJ]',40,13);
INSERT INTO "group"(id,name,members,parent_id) VALUES (16,'PDM 3. godina [M-Ž]',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (17,'PDM 3. godina [M-P]',40,16);
INSERT INTO "group"(id,name,members,parent_id) VALUES (18,'PDM 3. godina [R-Ž]',40,16);
INSERT INTO "group"(id,name,members,parent_id) VALUES (19,'PDM-N 1. godina [A-LJ]',50,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (20,'PDM-N 1. godina [A-H]',25,19);
INSERT INTO "group"(id,name,members,parent_id) VALUES (21,'PDM-N 1. godina [I-LJ]',25,19);
INSERT INTO "group"(id,name,members,parent_id) VALUES (22,'PDM-N 1. godina [M-Ž]',50,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (23,'PDM-N  1. godina [M-P]',25,22);
INSERT INTO "group"(id,name,members,parent_id) VALUES (24,'PDM-N  1. godina [R-Ž]',25,22);
INSERT INTO "group"(id,name,members,parent_id) VALUES (25,'PDM-N 2. godina',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (26,'PDM-N 2. godina [A-LJ]',40,25);
INSERT INTO "group"(id,name,members,parent_id) VALUES (27,'PDM-N 2. godina [M-Ž]',40,25);
INSERT INTO "group"(id,name,members,parent_id) VALUES (28,'PDM-N 3. godina',80,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (29,'PDM-N 3. godina [A-LJ]',40,28);
INSERT INTO "group"(id,name,members,parent_id) VALUES (30,'PDM-N 3. godina [M-Ž]',40,28);
INSERT INTO "group"(id,name,members,parent_id) VALUES (31,'DTM 1. godina',20,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (32,'DTM 2. godina',20,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (33,'DPM 1. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (34,'DPM 2. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (35,'DMS 1. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (36,'DMS 2. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (37,'DRM 1. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (38,'DRM 1. godina [A-LJ]',20,37);
INSERT INTO "group"(id,name,members,parent_id) VALUES (39,'DRM 1. godina [M-Ž]',20,37);
INSERT INTO "group"(id,name,members,parent_id) VALUES (40,'DRM 2. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (41,'DFPM 1. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (42,'DFPM 2. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (43,'DM-N 1. godina',60,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (44,'DM-N 1. godina [A-LJ]',30,43);
INSERT INTO "group"(id,name,members,parent_id) VALUES (45,'DM-N 1. godina [M-Ž]',30,43);
INSERT INTO "group"(id,name,members,parent_id) VALUES (46,'DM-N 2. godina',60,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (47,'DM-N 2. godina [A-LJ]',30,46);
INSERT INTO "group"(id,name,members,parent_id) VALUES (48,'DM-N 2. godina [M-Ž]',30,46);
INSERT INTO "group"(id,name,members,parent_id) VALUES (49,'DMI-N 1. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (50,'DMI-N 1. godina [A-LJ]',15,49);
INSERT INTO "group"(id,name,members,parent_id) VALUES (51,'DMI-N 1. godina [M-Ž]',15,49);
INSERT INTO "group"(id,name,members,parent_id) VALUES (52,'DMI-N 2. godina',30,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (53,'DMI-N 2. godina [A-LJ]',15,52);
INSERT INTO "group"(id,name,members,parent_id) VALUES (54,'DMI-N 2. godina [M-Ž]',15,52);
INSERT INTO "group"(id,name,members,parent_id) VALUES (55,'IMF-N 1. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (56,'IMF-N 2. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (57,'IMF-N 3. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (58,'IMF-N 4. godina',40,NULL);
INSERT INTO "group"(id,name,members,parent_id) VALUES (59,'IMF-N 5. godina',40,NULL);
